# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eea02b28e7de961962e866bbcc8782289dc6c8bab9a5a9f269259b8fed9e43a39ceb2c454a7116a9f3c9eb0a449040b3e93ac2534da9716a2b1b8ed4d1101b85

test:
  secret_key_base: d73c6a2241fe7575d8d738e62c640abb1fad666954a64d053d7aaada424eaa30fe2a827401cad66f60ee1b6a14553a8375b259ca2dc0a4db253c8f5a9242c787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
